spring.application.name=BankFlow-CQRS
server.port=8066

# spring.datasource.url=jdbc:h2:mem:accounts-db
# spring.h2.console.enabled=true

axon.serializer.events=jackson
axon.serializer.messages=xstream
axon.serializer.general=jackson

axon.axonserver.servers=192.168.0.185:8124

spring.datasource.url= ${DB_URL:jdbc:postgresql://192.168.0.185:5432/es-accounts_db}
spring.datasource.username=admin
spring.datasource.password=1234

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true